# Generated by Django 2.2 on 2020-01-10 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_identidad', models.CharField(max_length=20, verbose_name='Cédula de Identidad')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visitante_perfil', to='account.Perfil')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('docente', 'Docente'), ('obrero', 'Obrero'), ('administrativo', 'Administrativo')], default='docente', max_length=20)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_perfil', to='account.Perfil')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=20, verbose_name='Grado')),
                ('seccion', models.CharField(max_length=20, verbose_name='Sección')),
                ('turno', models.CharField(blank=True, choices=[('mañana', 'Mañana'), ('tarde', 'Tarde')], default='mañana', max_length=20)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante_perfil', to='account.Perfil')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='Bibliotecario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='users/pictures', verbose_name='Imagen de Perfil')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bibliotecario_perfil', to='account.Perfil')),
            ],
            options={
                'verbose_name': 'Bibliotecario',
                'verbose_name_plural': 'Bibliotecarios',
            },
        ),
    ]
