# Generated by Django 2.2 on 2020-01-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200111_0241'),
        ('account', '0002_auto_20200109_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='libros',
            field=models.ManyToManyField(to='catalog.EjemplarLibro'),
        ),
    ]
