# Generated by Django 2.2 on 2020-01-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200111_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('bibliotecario', 'Bibliotecario'), ('estudiante', 'Estudiante'), ('personal', 'Personal'), ('visitante', 'Visitante')], default='estudiante', max_length=20),
        ),
    ]
