# Generated by Django 2.2 on 2020-01-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_perfil_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cedula_identidad',
            field=models.CharField(max_length=20, unique=True, verbose_name='Cédula de Identidad'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='libros',
            field=models.ManyToManyField(blank=True, to='catalog.EjemplarLibro'),
        ),
    ]
