# Generated by Django 2.2 on 2020-01-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200113_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
