# Generated by Django 2.2 on 2020-01-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_perfil_libros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliotecario',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='turno',
            field=models.CharField(blank=True, choices=[('mañana', 'Mañana'), ('tarde', 'Tarde')], default='mañana', max_length=20, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cedula_identidad',
            field=models.CharField(max_length=12, unique=True, verbose_name='Cédula de Identidad'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('bibliotecario', 'Bibliotecario'), ('estudiante', 'Estudiante'), ('personal', 'Personal'), ('visitante', 'Visitante')], default='estudiante', max_length=20, verbose_name='Tipo de Usuario'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='tipo',
            field=models.CharField(blank=True, choices=[('docente', 'Docente'), ('obrero', 'Obrero'), ('administrativo', 'Administrativo')], default='docente', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
    ]
