# Generated by Django 2.2 on 2020-01-08 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_auto_20200107_2307'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('tipo_prestamo', models.CharField(blank=True, choices=[('aula', 'Aula'), ('Sala', 'Sala'), ('hogar', 'Hogar')], default='sala', help_text='Tipo de Prestamo', max_length=20)),
                ('fecha_prestamo', models.DateField(verbose_name='Fecha de Prestamo')),
                ('fecha_devolucion', models.DateField(verbose_name='Fecha de Devolución')),
                ('fecha_devuelto', models.DateField(verbose_name='Fecha de Devuelto')),
                ('bibliotecario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamo_bibliotecario', to=settings.AUTH_USER_MODEL)),
                ('ejemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamo_ejemplar', to='catalog.EjemplarLibro')),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamo_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
            },
        ),
    ]
