# Generated by Django 2.2 on 2020-01-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devuelto',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Devuelto'),
        ),
    ]
