# Generated by Django 2.2 on 2020-01-13 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_auto_20200107_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='bibliotecario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamo_bibliotecario', to='account.Bibliotecario'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='lector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamo_user', to='account.Perfil'),
        ),
    ]
