# Generated by Django 2.2 on 2020-01-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_auto_20200113_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devuelto',
            field=models.DateField(blank=True, null=True, verbose_name='Devuelto'),
        ),
    ]
