# Generated by Django 2.2 on 2020-01-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_auto_20200113_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='tipo_prestamo',
            field=models.CharField(blank=True, choices=[('aula', 'Aula'), ('sala', 'Sala'), ('hogar', 'Hogar')], default='sala', help_text='Tipo de Prestamo', max_length=20),
        ),
    ]
