# Generated by Django 2.2 on 2020-01-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_auto_20200120_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='tipo_prestamo',
            field=models.CharField(blank=True, choices=[('aula', 'Aula'), ('sala', 'Sala'), ('hogar', 'Hogar')], max_length=20),
        ),
    ]
