# Generated by Django 2.2 on 2020-01-23 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_perfil_libros'),
        ('catalog', '0016_ejemplarmaterial_nobibliografico'),
        ('loan', '0006_auto_20200121_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestamoMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('tipo_prestamo', models.CharField(blank=True, choices=[('aula', 'Aula'), ('sala', 'Sala'), ('hogar', 'Hogar')], max_length=20)),
                ('fecha_prestamo', models.DateField(verbose_name='Fecha de Prestamo')),
                ('fecha_devolucion', models.DateField(verbose_name='Fecha de Devolución')),
                ('fecha_devuelto', models.DateField(blank=True, null=True, verbose_name='Devuelto')),
                ('bibliotecario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_bibliotecario', to='account.Bibliotecario')),
                ('ejemplar_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_ejemplar', to='catalog.EjemplarLibro')),
                ('lector_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_user', to='account.Perfil')),
            ],
            options={
                'verbose_name': 'Prestamo Material',
                'verbose_name_plural': 'Prestamo Material',
            },
        ),
    ]
