# Generated by Django 2.2 on 2020-01-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0009_auto_20200125_0432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamomaterial',
            old_name='usuario',
            new_name='lector',
        ),
    ]
