# Generated by Django 2.2 on 2020-01-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='categoria',
            field=models.CharField(blank=True, choices=[('referencias', 'Referencias'), ('texto', 'Texto'), ('recreativo', 'Recreativo'), ('complementario', 'Complementario'), ('literatura', 'Literatura'), ('seccion docentes', 'Seccion Docentes')], default='referencias', help_text='Clasificación Dewey', max_length=20),
        ),
    ]
