# Generated by Django 2.2 on 2020-01-08 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200107_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjemplarLibro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('condicion', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('regular', 'Regular'), ('dañado', 'Dañado')], default='excelente', help_text='Condicion del ejemplar', max_length=20)),
                ('adquirido', models.CharField(blank=True, choices=[('donacion', 'Donacion'), ('comprado', 'Comprado')], default='donacion', help_text='Como fue adquirido el ejemplar', max_length=20)),
                ('estado', models.CharField(blank=True, choices=[('disponible', 'Disponible'), ('prestado', 'Prestado')], default='disponible', help_text='Disponibilidad del ejemplar', max_length=20)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplar_libro', to='catalog.Libro')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
