# Generated by Django 2.2 on 2020-01-08 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_ejemplarlibro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ejemplarlibro',
            options={'verbose_name': 'Ejemplar', 'verbose_name_plural': 'Ejemplares'},
        ),
    ]
