# Generated by Django 2.2 on 2020-01-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200107_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(upload_to='catalog/portadas', verbose_name='Portada del Libro'),
        ),
    ]
