# Generated by Django 2.2 on 2020-01-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200110_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='users/pictures', verbose_name='Portada del Libro'),
        ),
    ]
