# Generated by Django 2.2 on 2020-01-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200110_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/portadas', verbose_name='Portada del Libro'),
        ),
    ]
