# Generated by Django 2.2 on 2020-01-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200110_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='autor',
        ),
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.ManyToManyField(to='catalog.Autor'),
        ),
        migrations.RemoveField(
            model_name='libro',
            name='genero',
        ),
        migrations.AddField(
            model_name='libro',
            name='genero',
            field=models.ManyToManyField(to='catalog.Genero'),
        ),
    ]
