# Generated by Django 2.2 on 2020-01-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200113_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.FileField(blank=True, null=True, upload_to='catalog/portadas', verbose_name='Portada del Libro'),
        ),
    ]
