# Generated by Django 2.2 on 2020-01-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20200113_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/portadas', verbose_name='Portada del Libro'),
        ),
    ]
