# Generated by Django 2.2 on 2020-01-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20200113_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='genero',
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=150, verbose_name='Título del Libro'),
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
