# Generated by Django 2.2 on 2020-01-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20200120_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='categoria',
            field=models.CharField(blank=True, choices=[('referencia', 'Referencia'), ('complementarios', 'Complementarios'), ('recreativos', 'Recreativos'), ('textos', 'Textos'), ('pedagogicos', 'Pedagógicos'), ('publicaciones periodicas', 'Publicaciones Periodicas'), ('seccion docentes', 'Sección Docentes')], help_text='Clasificación Dewey', max_length=20),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='ubicacion',
            field=models.CharField(max_length=100, verbose_name='Ubicación'),
        ),
    ]
