# Generated by Django 2.2 on 2020-01-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200121_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplarlibro',
            name='cota',
            field=models.CharField(max_length=100, unique=True, verbose_name='Cota'),
        ),
    ]
