# Generated by Django 2.2 on 2020-01-23 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20200123_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoBibliografico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('material', models.CharField(max_length=100, verbose_name='Material')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('categoria', models.CharField(blank=True, choices=[('mapas', 'Mapas'), ('meni', 'Material Educativo no Impreso'), ('pizarra_magnetica', 'Pizarra Magnetica'), ('juegos', 'Juegos Didacticos'), ('otros', 'Otros')], max_length=20)),
            ],
            options={
                'verbose_name': 'Material no Bibliografico',
                'verbose_name_plural': 'Material no Bibliografico',
            },
        ),
        migrations.CreateModel(
            name='EjemplarMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('condicion', models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('regular', 'Regular'), ('dañado', 'Dañado')], default='excelente', help_text='Condicion del ejemplar', max_length=20)),
                ('adquirido', models.CharField(blank=True, choices=[('donacion', 'Donacion'), ('comprado', 'Comprado')], default='donacion', help_text='Como fue adquirido el ejemplar', max_length=20)),
                ('estado', models.CharField(blank=True, choices=[('disponible', 'Disponible'), ('prestado', 'Prestado')], default='disponible', help_text='Disponibilidad del ejemplar', max_length=20)),
                ('no_bibliografico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejemplar_material', to='catalog.NoBibliografico')),
            ],
            options={
                'verbose_name': 'Ejemplar no Bibliografico',
                'verbose_name_plural': 'Ejemplares no Bibliograficos',
            },
        ),
    ]
