# Generated by Django 2.2 on 2020-01-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_ejemplarmaterial_nobibliografico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ManyToManyField(related_name='libro_autor', to='catalog.Autor'),
        ),
    ]
