# Generated by Django 2.2 on 2020-01-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20200124_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='editorial',
            field=models.CharField(max_length=100, unique=True, verbose_name='Editorial'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='ubicacion',
            field=models.CharField(max_length=100, unique=True, verbose_name='Ubicación'),
        ),
    ]
