# Generated by Django 2.2 on 2020-01-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_auto_20200124_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/materiales', verbose_name='Imagen de Referencia'),
        ),
    ]
