# Generated by Django 2.2 on 2020-01-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_material_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='categoria',
            field=models.CharField(blank=True, choices=[('referencia', 'Referencia'), ('complementarios', 'Complementarios'), ('recreativos', 'Recreativos'), ('textos', 'Textos'), ('pedagogicos', 'Pedagógicos'), ('publicaciones periodicas', 'Publicaciones Periódicas'), ('seccion docentes', 'Sección Docentes')], help_text='Clasificación Dewey', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='categoria',
            field=models.CharField(blank=True, choices=[('mapas', 'Mapas'), ('meni', 'Material Educativo no Impreso'), ('juegos', 'Juegos Didácticos'), ('otros', 'Otros')], max_length=20),
        ),
    ]
